version: "3.5"

services:

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - "8998:80"
    restart: always
    networks:
      - def

networks:
  def:
    driver: bridge
