version: '3.7'


services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    restart: unless-stopped
    user: root
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      default:
        ipv4_address: ${DFLT_IP_JENKINS}
    volumes:
      - /etc/default/jenkins:/var/jenkins_home
      #- ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

networks:
  default:
    external: true