version: '3.7'


services:

  gitlab:
    container_name: gitlab
    hostname: 'gitlab.example.com'
    image: 'gitlab/gitlab-ee:latest'
    restart: unless-stopped
    #restart: always #video
    deploy:
      resources:
        limits:
          cpus: '1'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.${DOMAIN}'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['gitlab_signup_enabled'] = false
        letsencrypt['enable'] = false
        nginx['listen_port'] = ${GITLAB_PORT}
        nginx['listen_https'] = false
    networks:
      default:
        ipv4_address: ${DFLT_IP_GITLAB}
    volumes:
      - $GITLAB_VOLUME/config:/etc/gitlab:Z
      - $GITLAB_VOLUME/logs:/var/log/gitlab:Z
      - $GITLAB_VOLUME/data:/var/opt/gitlab:Z
    shm_size: '256m'


networks:
  default:
    external: true
    
volumes:
  gitlab_data:
  gitlab_config:
  gitlab_logs: