version: '3.7'


services:

  mongodb:
    container_name: logger_mongodb
    image: mongo:4.0.6
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=logger
    networks:
      - logger
    volumes:
      # seeding scripts
      - ${LOGGER_HOME}/entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - ${LOGGER_HOME}/data:/logger/data/db
      - ${LOGGER_HOME}/conf:/logger/data/configdb

  logger:
    container_name: logger
    image: cas.logger:1.0
    restart: always
    build:
      context: ./logger
      args:
          - REPO_BRANCH=${CAS_LOGGER_RELEASE}
          - SECRET_KEY=secret-key
          - SECURITY_PASSWORD_SALT=a324agfh[z
          - SECRET_DB_NAME=logger
    depends_on:
      - mongodb
    networks:
      - default
      - logger


networks:
  logger:
    name: logger-network
