{
 "title": "VSCode Exporter",
 "description": "Dashboard for VSCode Exporter metrics.",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Time Spent by Project",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(project) (increase(vscode_editor_seconds_active[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Spent by Action",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "sum(increase(vscode_editor_seconds_active[$__range])) > 0",
     "legendFormat": "Editing"
    },
    {
     "expr": "sum(increase(vscode_tasks_seconds_total[$__range])) > 0",
     "legendFormat": "Compiling"
    },
    {
     "expr": "sum(increase(vscode_debug_seconds_active[$__range])) > 0",
     "legendFormat": "Debugging"
    }
   ]
  },
  {
   "title": "Total Time Spent by Extension",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(extension) (label_replace(increase(vscode_editor_seconds_active{file=~\".*\\\\.([0-9a-z]+$)\"}[$__range]) > 0, \"extension\", \"$1\", \"file\", \".*\\\\.([0-9a-z]+$)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Spent by Project",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "sum by (project) (increase(vscode_editor_seconds_active[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Spent by Extension",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "sum by(extension) (label_replace(increase(vscode_editor_seconds_active{file=~\".*\\\\.([0-9a-z]+$)\"}[$__range]) > 0, \"extension\", \"$1\", \"file\", \".*\\\\.([0-9a-z]+$)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Line Changes by Project",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(project) (round(delta(vscode_lines_total[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Line Changes by Extension",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(extension) (label_replace(round(delta(vscode_lines_total{file=~\".*\\\\.([0-9a-z]+$)\"}[$__rate_interval])), \"extension\", \"$1\", \"file\", \".*\\\\.([0-9a-z]+$)\"))",
     "legendFormat": "{{extension}}"
    }
   ]
  },
  {
   "title": "Total Line Changes by Project",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(project) (sum_over_time((delta(vscode_lines_total[$__rate_interval]) < 0)[$__range:]))",
     "legendFormat": "Removed: {{project}}"
    },
    {
     "expr": "sum by(project) (sum_over_time((delta(vscode_lines_total[$__rate_interval]) > 0)[$__range:]))",
     "legendFormat": "Added: {{project}}"
    }
   ]
  },
  {
   "title": "Total Line Changes by Extension",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(extension) (label_replace(sum_over_time((delta(vscode_lines_total{file=~\".*\\\\.([0-9a-z]+$)\"}[$__rate_interval]) < 0)[$__range:]), \"extension\", \"$1\", \"file\", \".*\\\\.([0-9a-z]+$)\"))",
     "legendFormat": "Removed: {{extension}}"
    },
    {
     "expr": "sum by(extension) (label_replace(sum_over_time((delta(vscode_lines_total{file=~\".*\\\\.([0-9a-z]+$)\"}[$__rate_interval]) > 0)[$__range:]), \"extension\", \"$1\", \"file\", \".*\\\\.([0-9a-z]+$)\"))",
     "legendFormat": "Added: {{extension}}"
    }
   ]
  }
 ]
}