version: "3"

services:
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ee:latest'
    hostname: 'gitlab.example.com'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
