
services:

  mattermost-postgres:
    container_name: mattermost-postgres
    image: postgres:${MM_POSTGRES_IMAGE_TAG}
    pids_limit: 100
    read_only: true
    restart: ${MM_RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    env_file:
      - ./mattermost.env
    networks:
      - mattermost
    volumes:
      - ${MM_POSTGRES_DATA_PATH}:/var/lib/postgresql/data

  mattermost:
    container_name: mattermost
    depends_on:
      - mattermost-postgres
    image: mattermost/${MATTERMOST_IMAGE}:${MATTERMOST_IMAGE_TAG}
    restart: ${MM_RESTART_POLICY}
    pids_limit: 200
    read_only: ${MATTERMOST_CONTAINER_READONLY}
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    env_file:
      - ./mattermost.env
    networks:
      - mattermost
    #ports:
      # ports from docker-compose.without-nginx.yml
      #- ${MM_APP_PORT}:8065
      #- ${MM_CALLS_PORT}:${MM_CALLS_PORT}/udp
      #- ${MM_CALLS_PORT}:${MM_CALLS_PORT}/tcp
    volumes:
      - ${MATTERMOST_CONFIG_PATH}:/mattermost/config:rw
      - ${MATTERMOST_DATA_PATH}:/mattermost/data:rw
      - ${MATTERMOST_LOGS_PATH}:/mattermost/logs:rw
      - ${MATTERMOST_PLUGINS_PATH}:/mattermost/plugins:rw
      - ${MATTERMOST_CLIENT_PLUGINS_PATH}:/mattermost/client/plugins:rw
      - ${MATTERMOST_BLEVE_INDEXES_PATH}:/mattermost/bleve-indexes:rw
      # When you want to use SSO with GitLab, you have to add the cert pki chain of GitLab inside Alpine
      # to avoid Token request failed: certificate signed by unknown authority 
      # (link: https://github.com/mattermost/mattermost-server/issues/13059 and https://github.com/mattermost/docker/issues/34)
      # - ${GITLAB_PKI_CHAIN_PATH}:/etc/ssl/certs/pki_chain.pem:ro

